#include <stdio.h>

int main(void) {
    // Send the HTTP Content-Type header for HTML
    printf("Content-Type: text/html; charset=utf-8\n\n");

    // Print the HTML DOCTYPE and root elements
    printf("<!DOCTYPE html>\n");
    printf("<html lang=\"en\">\n");
    printf("<head>\n");
    printf("    <meta charset=\"UTF-8\">\n");
    printf("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    printf("    <title>Web App Programming & Hacking — Ian Cannon</title>\n");
    printf("</head>\n");
    printf("<body>\n");

    // Page heading and paragraph (as per W3Schools template)
    printf("    <h1>Welcome to Web App Programming &amp; Hacking</h1>\n");
    printf("    <p>This CGI page was generated by <strong>Ian Cannon</strong> for the Summer 2025 course.</p>\n");

    // Optionally, you can add more HTML here (images, links, etc.)
    printf("</body>\n");
    printf("</html>\n");

    return 0;
}
